
sudo: required
services:
  - docker
language: go
go:
  - '1.9'
  
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: L57n20eHHGJPa/psW9XtIWuZpMSOGEx5qTVtWdQrOk9EKaISAri2FpJ3xiItlupYHhkPX7rDQvJoojzyj5b5PqN0En+8+lU1hz3GxJvGNbpllfGNcuAcCyTNOL4pjlhOTFBX8HIMpkUad51h8UbJQ2ypiLo5GAHKS6N6vfNPduiA01CrmUNZ60GZgYQPTRwU237dSkriTjCqDgaBcKkQP8mcT8DeIXp9e+9zbjn3m1Axc8w41f0znT9IQA+tAjfh3a1ZUNvdj2TSmfz84nIScZxNaxu4++8wWF50SxD78gQlsRRJPLQP59bkM8tljXdnJ2ztjX9EyWRp715ipDkxzERzynN6uLQE10kKtTuKFF5/vINy+2j0FEg+5sy+sqF3uQIRyHyPgi22LH6NrGuufZWCdD+6oIKuq+0gpO3JBkMXR/On9xvRk1fnGBs/1Jq17vKAcDCj+QdegyTi3K8HerG1xFBT8S7xFSsTNCQtaGz/uJNBJSQW/S6fdtIaPxlSoVnAFr8Fmxeh7vbp0+FpVwQ8Isvj9+gLm67zoh6sChEA/9lMSOPA+tCnrbZqTlYBFLpNcRYAX05xFLNdh40Qe9um2xBNAvDfhwQQ5V4JFTCHnk09ys44phFV/jBqVF9eqv0yRndyJ5gexG1QLcpkksciZxr2sHc2zwSMWIxxuPM=
  - secure: mgknPSMf8zqVpO2ud9sQzOPyR/s7ZPYJHyJiWXwZkp6tC7pOXUxs5rkqjnVwVQnnU4dcAu8flxSI0m+zmnXBrlJjQbsnuu4s6yd5e/PcHDKXEV+aEodm0NF2kTHJPlFyWyAi7LzD8RRQMMNf7GqU81WUaBDr5WB2mwGZh/ObL8aw0AG8OEKY2ok4oCH9jSJwjSwXbUYkKE+TPIOJQNJxYooB3Kb2ozgb3d9/B7/IPn5Sx6gm5SkC99NcRTWSE1XYspmHZm9efu8Z1ZRXJMkwi95K0LT1pkU5GbjlhUTgV2qFx7SuKYfY1h0kEjmZHd82tHppLWpWZkjb96wEaeTbxR4aNpY3PudXpKMriVPudzu6r/ck28Mls76f93ShELkv+CL6ueovwlO0R+oINMh9ursnaXqppqeASxhaQZsZ/3YXQwT1Lk+0Iwg3XkhPTFcc0V7qg+KV03keqOGPSbMWzkUFgUnyobPLdEpD6oXXehVu8akNdUWZkbC/Qt9+oBOza4tAeAN9gegFlNH9bfZwpqTEPGlYOeC3TX/T2cKvXvpbCOAyIitXvMklWyb1cw5hhvbPGTFPnA87hHdQWS5Dd1XIrCH8FYBlB4ODEft6ibXqiIzOJgNoGrcLdz2vnmsPdMGWwiw1HY0LkV5DgmVdPu5U2aWDbUgdyXsySc9wLZU=
  - secure: Rg0tA6yUOAmkf4+A/5HPa642PpFQJdoOykGhLC/vvC5gMxDmoGuO/mRvqZMBA5c3unQ8vVmwvDTSyNNX0scE1oxXcqMa+yZtkXA6NiZZj3HpfPZd90lSY7zIQN3M09wEZ8izbT1mndd7S5hyDHhnndHUGRCEakLvyepZtuMPtUV77u9z7mW/a+CZZ7/Srg+ygg8AruG2fzOhEoX/39jyB0f0Rd4IAoaPgJT1uw60WiY4vF34ChD1SeSU+QZ4z5IXf6m29oVdmPpCCFbFIJVicMrU14wIIQDblKudDCTa3lKfigVLGHaPBgGizKMqNf+jwWqjr4yGxvTMSQOtdamzoVvfeYRXXxneA5Sa3UnAKH0iAkskFHJNHLFZHC2yJ/g3p1CbhqSZ6y/9OXUAKQDq+Gia73h1BpJN3S5c8KBql586H/a6YMGhXjrO2qhSRntoSJSZi9vElO0Nc7ojwp5urGfjz7tvZp7TX80BdJYXV12Gb9PbSStW2xuECSIy66XuqCSoKB5lWaV3uQhY1Pzq44ffYOaHyQPKseolrNfpDT98qaxCHfZJ5N5K75kBN25CFuI8MO3CFaDH1YGJ/1Z4OuNiROMVDn2Z3GaaXskbzhHDhhMe6qwNe2Mx+cxb+ZAFXW61bq9fQG55K42AcsvVYr7aZmaKqMZCJkJJlNB5sLU=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=sebestblog/travis-demo
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
